Move orientation and position to a combined "pose" type

diff --git a/bin/xr_driver_cli b/bin/xr_driver_cli
--- a/bin/xr_driver_cli
+++ b/bin/xr_driver_cli
@@ -1,5 +1,19 @@
 #!/usr/bin/env bash
 
+if ! systemctl --user --quiet is-active xr-driver >/dev/null 2>&1; then
+    if [ -z "$IGNORE_SYSTEMD_ERRORS" ]; then
+        echo "xr-driver service is not active. Start it with:" >&2
+        echo "  systemctl --user start xr-driver" >&2
+        echo ""
+        echo "If the issue persists, please create an issue on the wheaney/XRLinuxDriver repository."
+        echo ""
+        echo "To ignore this error, rerun with IGNORE_SYSTEMD_ERRORS=1"
+        exit 1
+    else
+        echo "Warning: xr-driver service is not active, most actions will be ineffective until this is resolved. Continuing due to IGNORE_SYSTEMD_ERRORS..." >&2
+    fi
+fi
+
 USER=${SUDO_USER:-$USER}
 USER_HOME=$(getent passwd $USER | cut -d: -f6)
 if [ -z "$XDG_CONFIG_HOME" ]; then
