Add SKIP_SYSTEMD support to setup, check for jq in the CLI, v2.4.3

diff --git a/bin/user/systemd_start b/bin/user/systemd_start
--- a/bin/user/systemd_start
+++ b/bin/user/systemd_start
@@ -8,6 +8,11 @@ if [ "$(id -u)" == "0" ]; then
    exit 1
 fi
 
+if ! command -v systemctl >/dev/null 2>&1; then
+  printf '\n\033[31mERROR\033[0m systemd was not found on this system. If you would still like to proceed without the background service, rerun this script with SKIP_SYSTEMD=1.\n'
+  exit 1
+fi
+
 echo "Setting up the systemd service"
 systemctl --user daemon-reload
 systemctl --user start xr-driver
diff --git a/bin/xr_driver_cli b/bin/xr_driver_cli
--- a/bin/xr_driver_cli
+++ b/bin/xr_driver_cli
@@ -206,6 +206,11 @@ then
                 hardware_id=$value
                 url="https://eu.driver-backend.xronlinux.com/tokens/v1"
 
+                if [[ "$1" == "--request-token" || "$1" == "--verify-token" ]] && ! command -v jq >/dev/null 2>&1; then
+                    echo "Error: jq utility not found. Install jq to use this feature." >&2
+                    exit 1
+                fi
+
                 if [ "$1" == "--request-token" ]; then
                     postbody=$(jq -n \
                                 --arg hardwareId "$hardware_id" \
